### ISSUE TITLE
Retirar 'PDT' da lista

### ISSUE THREAD

**Issue by ricsdeol** [torto/golpistas#1]
O PDT foi contra o golpe e esta para expulsar todos Senadores/Deputados que votaram a favor.
http://www.pdt.org.br/index.php/nota-oficial/

**Comment by torto** [comment]
Obrigado pela informação, irei remover :dancers:

**Comment by torto** [comment]
https://github.com/torto/golpistas/commit/4ac1bd29c56d064f16bb09e8fe1f97d7f510b510
